apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-aeks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-aeks
    app.kubernetes.io/part-of: tkrw-pr714-0075-0069-app
  name: devfile-sample-aeks
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-aeks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-aeks
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0069-tenant/tkrw-pr714-0075-0069-app/devfile-sample-aeks@sha256:1a2cf8249cc1c5200824ffbad8f10160d495a055154c8a9fefecf99f353474bf
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
